#pragma once
#define METHOD_NEITHER                  3
#define FILE_ANY_ACCESS                 0
#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
)

#define tKMD_DEVICE 0x8000

#define IOCTL_CALLBACK_PROCESS CTL_CODE(tKMD_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_CALLBACK_THREAD CTL_CODE(tKMD_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_CALLBACK_IMAGE CTL_CODE(tKMD_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_LIST_MODULES CTL_CODE(tKMD_DEVICE, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_CALLBACK_REMOVE CTL_CODE(tKMD_DEVICE, 0x804, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_WINDOWS_VERSION CTL_CODE(tKMD_DEVICE, 0x805, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_PS_PROTECTION CTL_CODE(tKMD_DEVICE, 0x806, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_SUPPORTED_VERSION CTL_CODE(tKMD_DEVICE, 0x807, METHOD_NEITHER, FILE_ANY_ACCESS)

typedef struct _MODULE_NAMES
{
    CHAR Name[256];
} MODULE_NAMES, * PMODULE_NAMES;

typedef struct _CALLBACK_INFO
{
    ULONG64 Address;
    CHAR Module[256];
} CALLBACK_INFO, *PCALLBACK_INFO;

typedef struct _TARGET_CALLBACK
{
    unsigned long long Address;
} TARGET_CALLBACK, * PTARGET_CALLBACK;

typedef struct _WINDOWS_VERSION
{
    ULONG MajorVersion;
    ULONG MinorVersion;
    ULONG BuildNumber;
} WINDOWS_VERSION, * PWINDOWS_VERSION;

typedef struct _PS_PROTECTION 
{
    UCHAR Level;
    UCHAR Type : 3;
    UCHAR Audit : 1;
    UCHAR Signer : 4;
} PS_PROTECTION, * PPS_PROTECTION;

typedef struct _TARGET_PROCESS
{
    int ProcessId;
} TARGET_PROCESS, * PTARGET_PROCESS;

typedef struct _OFFSET
{
    ULONG PROCESS_NOTIFY_OFFSET;
    ULONG THREAD_NOTIFY_OFFSET;
    ULONG IMAGE_NOTIFY_OFFSET;
    ULONG PS_PROTECTION_OFFSET;
} OFFSET, * POFFSET;