#pragma once
#define METHOD_NEITHER                  3
#define FILE_ANY_ACCESS                 0
#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
)

#define PROCESS_NOTIFY_OFFSET 0x7af280
#define THREAD_NOTIFY_OFFSET 0x7aee10
#define IMAGE_NOTIFY_OFFSET 0x7aef90

#define tKMD_DEVICE 0x8000

#define IOCTL_CALLBACK_PROCESS CTL_CODE(tKMD_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_CALLBACK_THREAD CTL_CODE(tKMD_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_CALLBACK_IMAGE CTL_CODE(tKMD_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_LIST_MODULES CTL_CODE(tKMD_DEVICE, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_CALLBACK_REMOVE CTL_CODE(tKMD_DEVICE, 0x804, METHOD_NEITHER, FILE_ANY_ACCESS)

typedef struct _MODULE_NAMES
{
    CHAR Name[256];
} MODULE_NAMES, * PMODULE_NAMES;

typedef struct _CALLBACK_INFO
{
    ULONG64 Address;
    CHAR Module[256];
} CALLBACK_INFO, *PCALLBACK_INFO;

typedef struct _TARGET_CALLBACK
{
    unsigned long long Address;
} TARGET_CALLBACK, * PTARGET_CALLBACK;