#pragma once

#define tKMD_DEVICE 0x8000
#define IOCTL_CALLBACK_PROCESS CTL_CODE(tKMD_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS);
#define IOCTL_CALLBACK_THREAD CTL_CODE(tKMD_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS);
#define IOCTL_CALLBACK_IMAGE CTL_CODE(tKMD_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS);